### ISSUE TITLE
Error when using rgb branch

### ISSUE THREAD

**Issue by ManuCart** [jorgebucaran/colorette#35]
````
npm install --save jorgebucaran/colorette#rgb
````

When try rgb colorette branch, I have this error

````
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '/home/dev/node_modules/colorette/test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
````

**Comment by jorgebucaran** [comment]
@ManuCart Installed it here (using node v11) and `require("colorette")` in a node REPL, but found no issues. What did you try?

Closing as this is most likely something in your end, and nothing I need to change in the library. Feel free to reopen if you disagree. 👋
