### ISSUE TITLE
 Bug: Package exports do not define a valid '.' target

### ISSUE THREAD

**Issue by Komaricus** [jorgebucaran/colorette#51]
Hi!

Trying to create new Vue application with vue-cli command `vue create brief-vue` and then run and got an error:

```
Error: Package exports for '/Users/aleksandr/Documents/brief-vue/node_modules/colorette' do not define a valid '.' target
Error: Package exports for '/Users/aleksandr/Documents/brief-vue/node_modules/colorette' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/aleksandr/Documents/brief-vue/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/aleksandr/Documents/brief-vue/node_modules/@vue/cli-service/lib/config/css.js:87:11
error Command failed with exit code 1.
```

Seems like the required file is missing: https://github.com/jorgebucaran/colorette/blob/master/package.json#L18

In my node_modules:

![image](https://user-images.githubusercontent.com/33253356/90131850-790c9000-dd75-11ea-805a-a9798cca6b6c.png)

Your .gitignore file:
![image](https://user-images.githubusercontent.com/33253356/90131895-8b86c980-dd75-11ea-8d8e-0b1ecfe252ac.png)

My setup:
macOS Catalina 10.15.6
yarn 1.22.4
node v14.8.0
@vue/cli 4.5.3

**Comment by jorgebucaran** [comment]
Hey @Komaricus, are you completely sure this is not a Node.js version related issue? https://github.com/jorgebucaran/colorette/issues/48

**Comment by Komaricus** [comment]
Thanks, upgrading node and `nvm use 14.8` already helped me
