### ISSUE TITLE
require() of ES modules is not supported

### ISSUE THREAD

**Issue by eng-dibo** [jorgebucaran/colorette#65]
I have an issue when I try to run webpack with `webpack.config.ts` written in typescript and `ts-node` has `"require": ["tsconfig-paths/register"]`

// tsconfig.json
```
{
  compilerOptions:{
    paths: { /* ----------------- */ }
  },
 'ts-node':{
   "require": ["tsconfig-paths/register"],
   "compilerOptions": {
      "sourceMap": false,
      "module": "commonjs"
    }
}
}
```

when I remove `"require": ["tsconfig-paths/register"]` from `ts-node` it runs, but webpack cannot detect aliases.

I already set `module: commonjs` in my `tsconfig.json` and removed `type: module` from my `package.json`

trace
```
> webpack

(node:5932) Warning: require() of ES modules is not supported.
require() of /home/node_modules/colorette/index.js from /home/node_modules/webpack-cli/lib/utils/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/node_modules/colorette/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/node_modules/colorette/package.json.
(node:5932) UnhandledPromiseRejectionWarning: /home/node_modules/colorette/index.js:28
export const options = Object.defineProperty({}, "enabled", {
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:84:7)
    at NativeCompileCache._moduleCompile (/home/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (/home/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.get colors [as colors] (/home/node_modules/webpack-cli/lib/utils/index.js:3:16)
    at Object.error (/home/node_modules/webpack-cli/lib/utils/logger.js:5:58)
(node:5932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by jorgebucaran** [comment]
Colorette should work out of the box on old Node because we define entry points for it [here](https://github.com/jorgebucaran/colorette/blob/eec128ebdc0e12c7bd0b7016270dc8081d81e096/package.json#L11-L17).

**Comment by eng-dibo** [comment]
ok, so how to solve this issue?
I use node v12.14.1

**Comment by jorgebucaran** [comment]
If you are importing an ES module in Node `v12.*` you also need to specify the [`--experimental-modules`](https://nodejs.org/dist./v12.12.0/docs/api/esm.html#esm_experimental_json_modules) flag when running your program. Did you try that?

**Comment by eng-dibo** [comment]
I use webpack which uses ts-node which registers tsconfig-paths which on its turn uses colorette.

I set `module: commonjs` to my tsconfig.json and can't require to use ES modules.

I don't run node by myself at all

**Comment by jorgebucaran** [comment]
`require`ing Colorette should work out of the box too. This is probably not a Colorette issue, I'm afraid.

<img width="1440" alt="Screen Shot 2021-09-12 at 23 04 00" src="https://user-images.githubusercontent.com/56996/132990686-95e2ebec-c23b-4588-a648-3bcfc9bde3a4.png">

**Comment by jorgebucaran** [comment]
`require`ing Colorette should work out of the box when using CommonJS. This looks like a webpack thing, so closing.
